[features]
seeds = false
skip-lint = false
[programs.localnet]
teaching_project_handler = "Hd3HLLMfbMJonaCvcQ8GugmTdKsGoHvce1JfAUU2gmiS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/canarionjl/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
